# Generated by Django 2.1.4 on 2019-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('0', 'ACTIVE'), ('1', 'DELETED'), ('2', 'ARCHIVED')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('employee', 'employee'), ('customer', 'customer')], default='customer', max_length=8),
        ),
    ]
