# Generated by Django 2.1.4 on 2019-01-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_incomehistory_profilecustomer_purchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.CharField(max_length=12)),
                ('symbol', models.CharField(default='USD', max_length=7)),
                ('rate', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.Customer')),
            ],
        ),
    ]
