# Generated by Django 2.1.4 on 2019-01-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0006_exchangerates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
