# Generated by Django 2.1.4 on 2019-01-09 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0009_orderposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(choices=[('mrs', 'Mrs.'), ('mr', 'Mr.'), ('na', '(n/a)')], default='na', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
