# Generated by Django 2.1.4 on 2019-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0012_remove_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address at the moment of purchase.', null=True),
        ),
    ]
